name: Test-all-versions
on:
  pull_request:
    branches: [main]

jobs:
  tav:
    name: run test-all-version (tav)
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm install --ignore-scripts
      - run: lerna bootstrap --since origin/main --include-dependencies
      - run: lerna run compile --since origin/main --include-dependencies
      - run: lerna run test-all-versions --since origin/main