name: Test-all-versions
on:
  pull_request:
    branches: [main]

jobs:
  tav:
    name: run test-all-version (tav)
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: echo ${{ github.repository }}
      - name: filterpath
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: main
          list-files: json
          filters: .github/workflows/test-all-versions.yml
          
  runtav:
    needs: tav
    strategy:
      matrix:
        pkg: ${{ fromJson(needs.tav.outputs.packages) || fromJson('[]') }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: npm install test-all-versions
      - run: npm run test-all-versions --if-present
        working-directory: ${{ matrix.pkg }}
